### ISSUE TITLE
Warning - 12200  Schema validation warning

### ISSUE THREAD

**Issue by gautam0209** [awslabs/amazon-lex-twilio-integration#1]
I am not able to get the response as SMS. The Twilio Debugger shows:
![image](https://user-images.githubusercontent.com/28671992/27513066-e8d2cc50-5926-11e7-98f1-a582fc30e434.png)

**Comment by kbash09** [comment]
It seems like the Body is enclosed in double quotes. See step #11 and #12 under the API Gateway section of the blogpost: https://aws.amazon.com/blogs/ai/integrate-your-amazon-lex-bot-with-any-messaging-service/
